import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(await readFile(resolve(root, "package.json"), "utf8"));

if (typeof packageJson.version !== "string" || packageJson.version.length === 0) {
  throw new Error("package.json must contain a non-empty version");
}

const output = `/** Generated by scripts/generate-version.mjs. Do not edit by hand. */\nexport const VERSION = ${JSON.stringify(packageJson.version)} as const;\n`;
const outputDir = resolve(root, "src/generated");
await mkdir(outputDir, { recursive: true });
await writeFile(resolve(outputDir, "version.ts"), output, "utf8");
